name: Expo Doctor (expo)

on:
  push:
    branches:
      - main
      - master
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  doctor:
    name: Expo Doctor (expo)
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: 🚑 Run Doctor Checks
        run: npx expo-doctor@latest